import jsPDF from 'jspdf';
import 'jspdf-autotable';

interface PlatformForm {
  intent: string;
  route: string;
  notes: string;
}

interface DistributionData {
  // Project info
  projectTitle: string;
  projectType: string;
  budgetTier: string;
  runtimeMinutes: string;
  languagePrimary: string;
  
  // Business
  logline: string;
  synopsisShort: string;
  genres: string[];
  toneKeywords: string[];
  comps: { title: string; year: string; why: string }[];
  credits: { personName: string; role: string; characterName: string; notableCredits: string; imdbUrl: string }[];
  
  // Platforms
  platformsSelected: string[];
  platformForms: Record<string, PlatformForm>;
  distributionGoal: string;
  rightsOfferType: string;
  territories: string;
  termMonths: string;
  
  // Legal
  chainOfTitleStatus: string;
  musicClearanceStatus: string;
  releasesStatus: string;
  eAndOStatus: string;
  knownClearanceRisks: string[];
  
  // Technical
  masterAvailable: string;
  masterFormat: string;
  masterResolution: string;
  masterFrameRate: string;
  audioDeliverables: string[];
  captionsAvailable: string;
  subtitleLanguages: string[];
  textlessElements: string;
  mAndETrack: string;
  qcDone: string;
  
  // Assets
  trailerFile: File | null;
  posterFile: File | null;
  keyArtFile: File | null;
  pressKitUrl: string;
  
  // Scores
  businessScore: number;
  legalScore: number;
  technicalScore: number;
  finalScore: number;
  readinessBand: string;
  hardStops: string[];
  
  // Branding
  companyLogo?: string;
}

const PLATFORMS: Record<string, string> = {
  netflix: "Netflix (SVOD)",
  hulu: "Hulu (SVOD)",
  apple_tv: "Apple TV / iTunes (TVOD)",
  amazon_prime: "Amazon Prime Video (SVOD/TVOD)",
  roku: "Roku Channel (AVOD/FAST)",
  tubi: "Tubi (AVOD)",
  pluto: "Pluto TV (FAST)",
  peacock: "Peacock (SVOD/AVOD)"
};

const getStatusLabel = (status: string): string => {
  const map: Record<string, string> = {
    complete: "Complete",
    partial: "Partial",
    missing: "Missing",
    unknown: "Unknown",
    in_place: "In Place",
    planned: "Planned",
    yes: "Yes",
    no: "No",
    in_progress: "In Progress"
  };
  return map[status] || status || "Not Set";
};

const getScoreColor = (score: number): [number, number, number] => {
  if (score >= 80) return [34, 197, 94]; // green
  if (score >= 60) return [59, 130, 246]; // blue
  if (score >= 40) return [245, 158, 11]; // amber
  return [239, 68, 68]; // red
};

export const exportDistributionReadinessToPDF = (data: DistributionData): void => {
  try {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'letter'
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  let yPosition = margin;

  const addNewPageIfNeeded = (requiredSpace: number = 20) => {
    if (yPosition > pageHeight - margin - requiredSpace) {
      doc.addPage();
      yPosition = margin;
    }
  };

  const addFooter = (pageNum: number, totalPages: number) => {
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Generated by Filmmaker Genius | ${new Date().toLocaleDateString()}`,
      margin,
      pageHeight - 10
    );
    doc.text(
      `Page ${pageNum} of ${totalPages}`,
      pageWidth - margin,
      pageHeight - 10,
      { align: 'right' }
    );
  };

  // ========== PAGE 1: Cover / Summary ==========
  
  // Add company logo if provided
  if (data.companyLogo) {
    try {
      const logoWidth = 50;
      const logoHeight = 15;
      const logoX = (pageWidth - logoWidth) / 2;
      doc.addImage(data.companyLogo, 'AUTO', logoX, yPosition, logoWidth, logoHeight);
      yPosition += logoHeight + 10;
    } catch (error) {
      console.error('Error adding logo to PDF:', error);
    }
  }

  // Title
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  
  // Dark header box
  const headerColor: [number, number, number] = [31, 41, 55];
  doc.setFillColor(...headerColor);
  doc.rect(0, yPosition - 5, pageWidth, 50, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.text("Distribution Readiness", pageWidth / 2, yPosition + 12, { align: 'center' });
  doc.setFontSize(18);
  doc.text("Report", pageWidth / 2, yPosition + 22, { align: 'center' });
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(156, 163, 175);
  doc.text(data.projectTitle || "Untitled Project", pageWidth / 2, yPosition + 35, { align: 'center' });
  
  yPosition += 60;

  // Overall Score - Large Display
  const scoreColor = getScoreColor(data.finalScore);
  doc.setFillColor(...scoreColor);
  doc.circle(pageWidth / 2, yPosition + 25, 25, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(36);
  doc.setFont('helvetica', 'bold');
  doc.text(String(data.finalScore), pageWidth / 2, yPosition + 30, { align: 'center' });
  
  yPosition += 55;
  
  // Readiness Band Badge
  doc.setFontSize(14);
  doc.setTextColor(...scoreColor);
  doc.text(data.readinessBand, pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 20;

  // Pillar Scores - Three columns
  doc.setTextColor(0, 0, 0);
  const colWidth = contentWidth / 3;
  
  const pillars = [
    { name: 'Business', score: data.businessScore, color: [59, 130, 246] as [number, number, number] },
    { name: 'Legal', score: data.legalScore, color: [168, 85, 247] as [number, number, number] },
    { name: 'Technical', score: data.technicalScore, color: [20, 184, 166] as [number, number, number] }
  ];
  
  pillars.forEach((pillar, index) => {
    const x = margin + (colWidth * index) + (colWidth / 2);
    
    doc.setFillColor(...pillar.color);
    doc.rect(margin + (colWidth * index) + 5, yPosition, colWidth - 10, 30, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text(String(pillar.score), x, yPosition + 15, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(pillar.name, x, yPosition + 24, { align: 'center' });
  });
  
  yPosition += 45;

  // Project Summary Box
  doc.setFillColor(249, 250, 251);
  doc.rect(margin, yPosition, contentWidth, 35, 'F');
  
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text("Project Summary", margin + 5, yPosition + 8);
  
  doc.setFont('helvetica', 'normal');
  const summaryItems = [
    `Type: ${data.projectType || 'Not Set'}`,
    `Runtime: ${data.runtimeMinutes || 'N/A'} minutes`,
    `Budget Tier: ${data.budgetTier || 'Not Set'}`,
    `Language: ${data.languagePrimary || 'Not Set'}`,
    `Platforms: ${data.platformsSelected.length} selected`
  ];
  
  let summaryY = yPosition + 15;
  summaryItems.forEach((item, i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    doc.text(item, margin + 5 + (col * (contentWidth / 2)), summaryY + (row * 6));
  });

  // ========== PAGE 2: Project Overview ==========
  doc.addPage();
  yPosition = margin;
  
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text("Project Overview", margin, yPosition);
  yPosition += 15;

  // Logline
  if (data.logline) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text("Logline", margin, yPosition);
    yPosition += 6;
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'italic');
    const loglineLines = doc.splitTextToSize(`"${data.logline}"`, contentWidth);
    doc.text(loglineLines, margin, yPosition);
    yPosition += (loglineLines.length * 5) + 8;
  }

  // Synopsis
  if (data.synopsisShort) {
    addNewPageIfNeeded(40);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text("Synopsis", margin, yPosition);
    yPosition += 6;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const synopsisLines = doc.splitTextToSize(data.synopsisShort, contentWidth);
    doc.text(synopsisLines, margin, yPosition);
    yPosition += (synopsisLines.length * 4) + 8;
  }

  // Genres & Tone
  if (data.genres.length > 0 || data.toneKeywords.length > 0) {
    addNewPageIfNeeded(25);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text("Genres & Tone", margin, yPosition);
    yPosition += 6;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    if (data.genres.length > 0) {
      doc.text(`Genres: ${data.genres.join(', ')}`, margin, yPosition);
      yPosition += 5;
    }
    if (data.toneKeywords.length > 0) {
      doc.text(`Tone: ${data.toneKeywords.join(', ')}`, margin, yPosition);
      yPosition += 5;
    }
    yPosition += 8;
  }

  // Key Credits
  if (data.credits.length > 0) {
    addNewPageIfNeeded(40);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text("Key Credits", margin, yPosition);
    yPosition += 8;
    
    const creditData = data.credits.map(c => [
      c.role || '',
      c.personName || '',
      c.characterName || '',
      c.notableCredits || '',
      c.imdbUrl || ''
    ]);
    
    (doc as any).autoTable({
      startY: yPosition,
      head: [['Role', 'Name', 'Character', 'Notable Credits', 'IMDb']],
      body: creditData,
      margin: { left: margin, right: margin },
      styles: { fontSize: 8 },
      headStyles: { fillColor: [31, 41, 55] },
      theme: 'grid',
      columnStyles: { 4: { cellWidth: 45 } }
    });
    
    yPosition = (doc as any).lastAutoTable.finalY + 10;
  }

  // Comparables
  if (data.comps.length > 0) {
    addNewPageIfNeeded(40);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text("Comparable Titles", margin, yPosition);
    yPosition += 8;
    
    const compData = data.comps.map(c => [c.title, c.year, c.why]);
    
    (doc as any).autoTable({
      startY: yPosition,
      head: [['Title', 'Year', 'Why It\'s Comparable']],
      body: compData,
      margin: { left: margin, right: margin },
      styles: { fontSize: 9 },
      headStyles: { fillColor: [31, 41, 55] },
      theme: 'grid'
    });
    
    yPosition = (doc as any).lastAutoTable.finalY + 10;
  }

  // ========== PAGE 3: Deal Killers & Warnings ==========
  doc.addPage();
  yPosition = margin;
  
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text("Status & Warnings", margin, yPosition);
  yPosition += 15;

  // Deal Killers
  if (data.hardStops.length > 0) {
    doc.setFillColor(254, 226, 226);
    doc.rect(margin, yPosition, contentWidth, 8 + (data.hardStops.length * 8), 'F');
    
    doc.setTextColor(185, 28, 28);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text("⚠ Deal Killers", margin + 5, yPosition + 6);
    yPosition += 12;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    data.hardStops.forEach(stop => {
      const lines = doc.splitTextToSize(`• ${stop}`, contentWidth - 10);
      doc.text(lines, margin + 5, yPosition);
      yPosition += lines.length * 5;
    });
    yPosition += 10;
  } else {
    doc.setFillColor(220, 252, 231);
    doc.rect(margin, yPosition, contentWidth, 15, 'F');
    doc.setTextColor(22, 101, 52);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text("✓ No Deal Killers Detected", margin + 5, yPosition + 10);
    yPosition += 25;
  }

  // Legal Status Summary
  addNewPageIfNeeded(50);
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text("Legal & Rights Status", margin, yPosition);
  yPosition += 8;

  const legalItems = [
    ['Chain of Title', getStatusLabel(data.chainOfTitleStatus)],
    ['Music Clearances', getStatusLabel(data.musicClearanceStatus)],
    ['Talent/Location Releases', getStatusLabel(data.releasesStatus)],
    ['E&O Insurance', getStatusLabel(data.eAndOStatus)]
  ];
  
  (doc as any).autoTable({
    startY: yPosition,
    head: [['Item', 'Status']],
    body: legalItems,
    margin: { left: margin, right: margin },
    styles: { fontSize: 10 },
    headStyles: { fillColor: [168, 85, 247] },
    theme: 'grid',
    columnStyles: { 0: { cellWidth: 80 } }
  });
  
  yPosition = (doc as any).lastAutoTable.finalY + 15;

  // ========== PAGE 4: Platform Checklists ==========
  addNewPageIfNeeded(60);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text("Platform Readiness Checklists", margin, yPosition);
  yPosition += 10;

  if (data.platformsSelected.length === 0) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.text("No platforms selected.", margin, yPosition);
    yPosition += 10;
  } else {
    data.platformsSelected.forEach(platformId => {
      addNewPageIfNeeded(40);
      const platformLabel = PLATFORMS[platformId] || platformId;
      
      doc.setFillColor(243, 244, 246);
      doc.rect(margin, yPosition, contentWidth, 8, 'F');
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 0, 0);
      doc.text(platformLabel, margin + 3, yPosition + 6);
      yPosition += 12;
      
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      
      const checkItems = [
        { label: 'Trailer', ready: !!data.trailerFile },
        { label: 'Artwork/Metadata', ready: !!(data.posterFile || data.keyArtFile) },
        { label: 'Captions/CC', ready: data.captionsAvailable === 'yes' },
        { label: 'Chain of Title', ready: data.chainOfTitleStatus === 'complete' },
        { label: 'E&O Insurance', ready: data.eAndOStatus === 'in_place' },
        { label: 'Master Available', ready: data.masterAvailable === 'yes' },
        { label: 'QC Complete', ready: data.qcDone === 'yes' }
      ];
      
      checkItems.forEach(item => {
        const icon = item.ready ? '✓' : '○';
        doc.setTextColor(item.ready ? 22 : 156, item.ready ? 101 : 163, item.ready ? 52 : 175);
        doc.text(`  ${icon} ${item.label}`, margin + 5, yPosition);
        yPosition += 5;
      });
      
      yPosition += 8;
    });
  }

  // ========== PAGE 5: Technical Deliverables ==========
  doc.addPage();
  yPosition = margin;
  
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text("Technical Deliverables", margin, yPosition);
  yPosition += 15;

  const techItems = [
    ['Master Available', getStatusLabel(data.masterAvailable)],
    ['Master Format', data.masterFormat || 'Not Set'],
    ['Master Resolution', data.masterResolution || 'Not Set'],
    ['Frame Rate', data.masterFrameRate || 'Not Set'],
    ['Audio Deliverables', data.audioDeliverables.join(', ') || 'None'],
    ['Captions Available', getStatusLabel(data.captionsAvailable)],
    ['Subtitle Languages', data.subtitleLanguages.join(', ') || 'None'],
    ['Textless Elements', getStatusLabel(data.textlessElements)],
    ['M&E Track', getStatusLabel(data.mAndETrack)],
    ['QC Complete', getStatusLabel(data.qcDone)]
  ];

  (doc as any).autoTable({
    startY: yPosition,
    head: [['Specification', 'Value']],
    body: techItems,
    margin: { left: margin, right: margin },
    styles: { fontSize: 10 },
    headStyles: { fillColor: [20, 184, 166] },
    theme: 'grid',
    columnStyles: { 0: { cellWidth: 60 } }
  });
  
  yPosition = (doc as any).lastAutoTable.finalY + 15;

  // Marketing Assets
  addNewPageIfNeeded(40);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text("Marketing Assets", margin, yPosition);
  yPosition += 8;

  const assetItems = [
    ['Trailer', data.trailerFile ? 'Uploaded' : 'Missing'],
    ['Poster/Key Art', (data.posterFile || data.keyArtFile) ? 'Uploaded' : 'Missing'],
    ['Press Kit', data.pressKitUrl || 'Not Provided']
  ];

  (doc as any).autoTable({
    startY: yPosition,
    head: [['Asset', 'Status']],
    body: assetItems,
    margin: { left: margin, right: margin },
    styles: { fontSize: 10 },
    headStyles: { fillColor: [31, 41, 55] },
    theme: 'grid'
  });

  // ========== PAGE 6: Next Steps ==========
  doc.addPage();
  yPosition = margin;
  
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text("Recommended Next Steps", margin, yPosition);
  yPosition += 15;

  const nextSteps: string[] = [];
  
  if (data.hardStops.length > 0) {
    nextSteps.push("Address all deal-killers listed in this report before proceeding with platform outreach.");
  }
  if (data.captionsAvailable !== 'yes') {
    nextSteps.push("Complete captions/closed captions for your project. This is required by most major platforms.");
  }
  if (data.chainOfTitleStatus !== 'complete') {
    nextSteps.push("Finalize your chain of title documentation with qualified legal counsel.");
  }
  if (data.eAndOStatus === 'missing') {
    nextSteps.push("Obtain Errors & Omissions insurance - this is required for most distribution deals.");
  }
  if (!data.trailerFile) {
    nextSteps.push("Create and prepare a professional trailer for marketing and platform submissions.");
  }
  if (data.masterAvailable !== 'yes') {
    nextSteps.push("Ensure your master file is properly archived and accessible for delivery.");
  }
  if (data.qcDone !== 'yes') {
    nextSteps.push("Complete quality control (QC) review of your final master.");
  }
  nextSteps.push("Research aggregators and distributors that specialize in your target platforms.");
  nextSteps.push("Prepare platform-specific metadata packages and submission materials.");

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  
  nextSteps.forEach((step, index) => {
    addNewPageIfNeeded(15);
    doc.setFillColor(249, 250, 251);
    const stepLines = doc.splitTextToSize(step, contentWidth - 20);
    const boxHeight = 8 + (stepLines.length * 4);
    doc.rect(margin, yPosition, contentWidth, boxHeight, 'F');
    
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'bold');
    doc.text(`${index + 1}.`, margin + 3, yPosition + 6);
    doc.setFont('helvetica', 'normal');
    doc.text(stepLines, margin + 12, yPosition + 6);
    
    yPosition += boxHeight + 4;
  });

  // Add footer disclaimer
  yPosition += 10;
  addNewPageIfNeeded(20);
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  const disclaimer = "This report is for informational purposes only and does not constitute legal or business advice. Consult qualified professionals for specific guidance on distribution agreements and legal matters.";
  const disclaimerLines = doc.splitTextToSize(disclaimer, contentWidth);
  doc.text(disclaimerLines, margin, yPosition);

  // Add footers to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(i, totalPages);
  }

    // Save
    const fileName = `Distribution_Readiness_${data.projectTitle?.replace(/[^a-zA-Z0-9]/g, '_') || 'Report'}_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
  } catch (error) {
    console.error('PDF generation error:', error);
    throw new Error('Failed to generate PDF report');
  }
};

export const generateDistributionPDFBlob = async (data: DistributionData): Promise<Blob> => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'letter'
  });

  // Use same logic as exportDistributionReadinessToPDF but return blob
  // For email attachment purposes
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  let yPosition = margin;

  // Simplified version for email - just cover page + summary
  if (data.companyLogo) {
    try {
      doc.addImage(data.companyLogo, 'AUTO', (pageWidth - 50) / 2, yPosition, 50, 15);
      yPosition += 25;
    } catch (e) {
      console.error('Logo error:', e);
    }
  }

  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text("Distribution Readiness Report", pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;
  
  doc.setFontSize(16);
  doc.setFont('helvetica', 'normal');
  doc.text(data.projectTitle || "Untitled Project", pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 20;

  doc.setFontSize(48);
  doc.setFont('helvetica', 'bold');
  const scoreColor = getScoreColor(data.finalScore);
  doc.setTextColor(...scoreColor);
  doc.text(String(data.finalScore), pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 10;
  
  doc.setFontSize(14);
  doc.text(data.readinessBand, pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 20;

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.text(`Business: ${data.businessScore}%  |  Legal: ${data.legalScore}%  |  Technical: ${data.technicalScore}%`, pageWidth / 2, yPosition, { align: 'center' });

  return doc.output('blob');
};
