import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface Shot {
  shotNumber: number;
  description?: string;
  cameraAngle?: string;
  characters?: string[];
  visualElements?: string;
  duration?: string;
  visualDescription?: string;
  location?: string;
  action?: string;
  emotionalTone?: string;
  shotType?: string;
  lighting?: string;
  keyProps?: string;
  dialogue?: string;
}

interface StoryboardFrame {
  shotNumber: number;
  imageData?: string;
}

interface ExportOptions {
  projectName?: string;
  genre?: string;
  tone?: string;
  includeImages?: boolean;
}

export const exportShotListToPDF = async (
  shots: Shot[],
  frames?: StoryboardFrame[],
  options: ExportOptions = {}
) => {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4'
  });

  const projectName = options.projectName || 'Untitled Project';
  const currentDate = new Date().toLocaleDateString();

  // Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(projectName, 14, 15);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Shot List - ${currentDate}`, 14, 22);
  
  if (options.genre || options.tone) {
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text(`Genre: ${options.genre || 'N/A'} | Tone: ${options.tone || 'N/A'}`, 14, 27);
  }

  // Table data
  const tableData = shots.map(shot => {
    const frame = frames?.find(f => f.shotNumber === shot.shotNumber);
    return [
      shot.shotNumber.toString(),
      shot.shotType || shot.cameraAngle || 'N/A',
      shot.cameraAngle || 'N/A',
      (shot.visualDescription || shot.description || '').substring(0, 100) + ((shot.visualDescription || shot.description || '').length > 100 ? '...' : ''),
      shot.action || 'N/A',
      shot.characters?.join(', ') || 'N/A',
      shot.location || 'N/A',
      shot.dialogue || 'None',
      shot.duration || 'N/A'
    ];
  });

  autoTable(doc, {
    startY: 32,
    head: [[
      'Shot #',
      'Shot Type',
      'Camera',
      'Description',
      'Action',
      'Characters',
      'Location',
      'Dialogue',
      'Duration'
    ]],
    body: tableData,
    headStyles: {
      fillColor: [30, 30, 30],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8
    },
    bodyStyles: {
      fontSize: 7,
      cellPadding: 2
    },
    columnStyles: {
      0: { cellWidth: 12, halign: 'center' },
      1: { cellWidth: 22 },
      2: { cellWidth: 22 },
      3: { cellWidth: 50 },
      4: { cellWidth: 35 },
      5: { cellWidth: 25 },
      6: { cellWidth: 30 },
      7: { cellWidth: 40 },
      8: { cellWidth: 15, halign: 'center' }
    },
    alternateRowStyles: {
      fillColor: [245, 245, 245]
    },
    margin: { left: 10, right: 10 }
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${pageCount} | Generated by Feifer Film Toolbox`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 7,
      { align: 'center' }
    );
  }

  doc.save(`${projectName.replace(/\s+/g, '_')}_shot_list.pdf`);
};

export const exportDetailedShotListToPDF = async (
  shots: Shot[],
  frames?: StoryboardFrame[],
  options: ExportOptions = {}
) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const projectName = options.projectName || 'Untitled Project';
  const currentDate = new Date().toLocaleDateString();
  
  let yPosition = 15;
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;

  const addHeader = () => {
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(projectName, margin, yPosition);
    yPosition += 6;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Detailed Shot List - ${currentDate}`, margin, yPosition);
    yPosition += 4;
    
    if (options.genre || options.tone) {
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      doc.text(`Genre: ${options.genre || 'N/A'} | Tone: ${options.tone || 'N/A'}`, margin, yPosition);
      doc.setTextColor(0, 0, 0);
    }
    yPosition += 10;
  };

  addHeader();

  for (let i = 0; i < shots.length; i++) {
    const shot = shots[i];
    const frame = frames?.find(f => f.shotNumber === shot.shotNumber);
    
    // Check if we need a new page
    if (yPosition > pageHeight - 80) {
      doc.addPage();
      yPosition = 15;
    }

    // Shot header
    doc.setFillColor(30, 30, 30);
    doc.rect(margin, yPosition - 5, pageWidth - (margin * 2), 8, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text(`SHOT ${shot.shotNumber}`, margin + 3, yPosition);
    doc.text(shot.shotType || shot.cameraAngle || '', pageWidth - margin - 40, yPosition);
    doc.setTextColor(0, 0, 0);
    yPosition += 8;

    // Shot image thumbnail (if available and includeImages is true)
    const imageWidth = 50;
    let contentStartX = margin;
    
    if (options.includeImages && frame?.imageData) {
      try {
        doc.addImage(frame.imageData, 'PNG', margin, yPosition, imageWidth, imageWidth * 0.5625);
        contentStartX = margin + imageWidth + 5;
      } catch (e) {
        console.warn('Failed to add image to PDF', e);
      }
    }

    // Shot details
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    let textY = yPosition + 3;
    
    const addField = (label: string, value: string | undefined) => {
      if (!value || value === 'N/A') return;
      doc.setFont('helvetica', 'bold');
      doc.text(`${label}: `, contentStartX, textY);
      doc.setFont('helvetica', 'normal');
      
      const labelWidth = doc.getTextWidth(`${label}: `);
      const maxWidth = pageWidth - contentStartX - margin - labelWidth;
      const lines = doc.splitTextToSize(value, maxWidth);
      doc.text(lines, contentStartX + labelWidth, textY);
      textY += lines.length * 3.5;
    };

    addField('Camera', shot.cameraAngle);
    addField('Location', shot.location);
    addField('Characters', shot.characters?.join(', '));
    addField('Action', shot.action);
    addField('Lighting', shot.lighting);
    addField('Props', shot.keyProps);
    addField('Dialogue', shot.dialogue);
    addField('Mood', shot.emotionalTone);

    // Description
    if (shot.visualDescription || shot.description) {
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(7);
      const descLines = doc.splitTextToSize(
        shot.visualDescription || shot.description || '',
        pageWidth - (margin * 2)
      );
      doc.text(descLines, margin, textY + 3);
      textY += descLines.length * 3;
    }

    yPosition = Math.max(textY, options.includeImages && frame?.imageData ? yPosition + 35 : textY) + 10;

    // Divider
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, yPosition - 5, pageWidth - margin, yPosition - 5);
  }

  // Footer on all pages
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${pageCount} | ${projectName} | Generated by Feifer Film Toolbox`,
      pageWidth / 2,
      pageHeight - 7,
      { align: 'center' }
    );
  }

  doc.save(`${projectName.replace(/\s+/g, '_')}_detailed_shot_list.pdf`);
};
